# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addressbook.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("addressbook.proto", :syntax => :proto3) do
    add_message "proto.Person" do
      optional :name, :string, 1
      optional :id, :int32, 2
      optional :email, :string, 3
      repeated :phones, :message, 4, "proto.Person.PhoneNumber"
    end
    add_message "proto.Person.PhoneNumber" do
      optional :number, :string, 1
      optional :type, :enum, 2, "proto.Person.PhoneType"
    end
    add_enum "proto.Person.PhoneType" do
      value :MOBILE, 0
      value :HOME, 1
      value :WORK, 2
    end
    add_message "proto.AddressBook" do
      repeated :people, :message, 1, "proto.Person"
    end
  end
end

module Proto
  Person = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Person").msgclass
  Person::PhoneNumber = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Person.PhoneNumber").msgclass
  Person::PhoneType = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.Person.PhoneType").enummodule
  AddressBook = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("proto.AddressBook").msgclass
end
